
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-Org-GETPUTDELETE","number":60,"title":"LW - create GET endpoint for single record on Organizations","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/60"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"Liz-UCSBDiningCommonsMenuItem-controller-get-post","number":56,"title":"liz - UCSBDiningCommonsMenuItem controller, get all, post","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/56"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"Liz-UCSBDiningCommonsMenuItem-create-db","number":54,"title":"liz - create db for ucsb dining commons menu items","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/54"},{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"Yuji-MenuItemReviews-GET-PUT-DELETE","number":53,"title":"Yuji MenuItemReview GET, PUT, DELETE","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/53"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-UCSBOrganizationController","number":50,"title":"LW - Add controller, GET and POST, and tests for UCSBOrganizations","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/50"}]
