
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-OrganizationsTable","number":48,"title":"lw - UCSBOrganizations setup, added entity, repository, and migration","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/48"},{"author":{"id":"MDQ6VXNlcjU1NjAyNjE0","is_bot":false,"login":"jeffsmithepic","name":"wchiba"},"headRefName":"Wesley-HelpRequest-create-db","number":47,"title":"WC - add HelpRequest entity, repository, and db migration","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/47"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-PUT-Articles","number":46,"title":"Diya put articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/46"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-DELETE-Articles","number":45,"title":"Diya delete articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/45"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-GET-Articles","number":44,"title":"Diya get single articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/44"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-Article-CreateDB","number":43,"title":"Diya article create db","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-6/pull/43"}]
